<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- RPLidar A1 Physical Properties -->
    <xacro:property name="lidar_a1_diameter" value="0.115"/>  <!-- 115mm diameter -->
    <xacro:property name="lidar_a1_height" value="0.04"/>     <!-- 40mm height -->
    <xacro:property name="lidar_a1_mass" value="0.19"/>       <!-- 190g weight -->
    <xacro:property name="lidar_a1_radius" value="${lidar_a1_diameter/2}"/>
    
    <!-- Lidar mounting position -->
    <xacro:property name="lidar_mount_height" value="0.1"/>   <!-- Mounting height from base -->
    
    <!-- Joint for A1 Lidar -->
    <joint name="lidar_a1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_a1_link"/>
        <origin xyz="0 0 ${lidar_mount_height + lidar_a1_height/2}" rpy="0 0 0"/>
    </joint>

    <!-- A1 Lidar Link -->
    <link name="lidar_a1_link">
        <!-- Main body visual -->
        <visual>
            <geometry>
                <cylinder radius="${lidar_a1_radius}" length="${lidar_a1_height}"/>
            </geometry>
            <material name="Black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </visual>
        
        <!-- Top cover visual -->
        <visual>
            <origin xyz="0 0 ${lidar_a1_height/2 + 0.001}"/>
            <geometry>
                <cylinder radius="${lidar_a1_radius}" length="0.002"/>
            </geometry>
            <material name="DarkGray">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        
        <!-- Collision geometry -->
        <collision>
            <geometry>
                <cylinder radius="${lidar_a1_radius}" length="${lidar_a1_height}"/>
            </geometry>
        </collision>
        
        <!-- Inertial properties -->
        <xacro:inertial_cylinder mass="${lidar_a1_mass}" length="${lidar_a1_height}" radius="${lidar_a1_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Laser frame for sensor data -->
    <link name="laser"/>
    
    <joint name="laser_joint" type="fixed">
        <parent link="lidar_a1_link"/>
        <child link="laser"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

</robot> 