turtlebot3_node:
  ros__parameters:

    opencr:
      id: 200
      baud_rate: 1000000
      protocol_version: 2.0

    wheels:
      # ▼▼ 수정: 4륜 구동용 휠 파라미터
      separation: 0.15  # 4륜 로봇용 좌우 휠 간격 (기존 0.160에서 수정)
      radius: 0.03      # 4륜 로봇용 휠 반지름 (기존 0.033에서 수정)

    motors:
      profile_acceleration_constant: 214.577

      # [rev/min2]
      # ref) http://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#profile-acceleration
      profile_acceleration: 0.0

    sensors:
      bumper_1: 0
      bumper_2: 0
      illumination: 0
      ir: 0
      sonar: 0

diff_drive_controller:
  ros__parameters:

    odometry:
      publish_tf: true
      use_imu: true
      frame_id: "odom"
      child_frame_id: "base_footprint"
